# Set root logger level to INFO and append to stdout
log4j.rootLogger=INFO, stdout

# Console appender configuration
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Flink specific logger configurations
log4j.logger.org.apache.flink=INFO
log4j.logger.org.apache.flink.table=INFO
log4j.logger.org.apache.calcite=INFO
log4j.logger.org.apache.kafka=WARN
log4j.logger.org.apache.hadoop=WARN
log4j.logger.com.clickhouse=WARN